import type { Template } from "./types";

export const comprehensiveMedicalExam: Template = {
  id: "comprehensive-medical-exam",
  nameKey: "comprehensive-medical-exam.name",
  descriptionKey: "comprehensive-medical-exam.description",
  specialties: ["general_practice", "internal_medicine"],
  isSystem: true,
  sortOrder: 0,
  sections: [
    { id: "reason_for_contact", labelKey: "reason_for_contact" },
    { id: "past_history", labelKey: "past_history" },
    { id: "assistive_devices", labelKey: "assistive_devices" },
    { id: "family_history", labelKey: "family_history" },
    { id: "allergies", labelKey: "allergies" },
    { id: "current_medications", labelKey: "current_medications" },
    {
      id: "social_history",
      labelKey: "social_history",
      subsections: [
        { id: "tobacco", labelKey: "tobacco" },
        { id: "alcohol", labelKey: "alcohol" },
        { id: "controlled_substances", labelKey: "controlled_substances" },
        { id: "physical_activity", labelKey: "physical_activity" },
        { id: "diet", labelKey: "diet" },
      ],
    },
    { id: "history_present_illness", labelKey: "history_present_illness" },
    {
      id: "physical_exam",
      labelKey: "physical_exam",
      subsections: [
        { id: "general_condition", labelKey: "general_condition" },
        { id: "body_temp", labelKey: "body_temp" },
        { id: "height", labelKey: "height" },
        { id: "weight", labelKey: "weight" },
        { id: "bmi", labelKey: "bmi" },
        { id: "skin", labelKey: "skin" },
        { id: "eyes", labelKey: "eyes" },
        { id: "ears", labelKey: "ears" },
        { id: "nose", labelKey: "nose" },
        { id: "mouth_throat", labelKey: "mouth_throat" },
        { id: "lymph_nodes", labelKey: "lymph_nodes" },
        { id: "thyroid", labelKey: "thyroid" },
        { id: "breast_exam", labelKey: "breast_exam" },
        { id: "heart", labelKey: "heart" },
        { id: "pulse", labelKey: "pulse" },
        { id: "blood_pressure", labelKey: "blood_pressure" },
        { id: "peripheral_pulses", labelKey: "peripheral_pulses" },
        { id: "ecg", labelKey: "ecg" },
        { id: "lungs", labelKey: "lungs" },
        { id: "respiratory_rate", labelKey: "respiratory_rate" },
        { id: "spo2", labelKey: "spo2" },
        { id: "abdomen", labelKey: "abdomen" },
        { id: "rectal_exam", labelKey: "rectal_exam" },
        { id: "gynaecology", labelKey: "gynaecology" },
        { id: "penis_scrotum", labelKey: "penis_scrotum" },
        { id: "neurological", labelKey: "neurological" },
        { id: "mental_state_exam", labelKey: "mental_state_exam" },
        { id: "suicide_risk_assessment", labelKey: "suicide_risk_assessment" },
        { id: "neck", labelKey: "neck" },
        { id: "back", labelKey: "back" },
        { id: "shoulders", labelKey: "shoulders" },
        { id: "elbows", labelKey: "elbows" },
        { id: "hands", labelKey: "hands" },
        { id: "hips", labelKey: "hips" },
        { id: "knees", labelKey: "knees" },
        { id: "feet", labelKey: "feet" },
      ],
    },
    { id: "lab", labelKey: "lab" },
    { id: "radiology", labelKey: "radiology" },
    { id: "other_exam_findings", labelKey: "other_exam_findings" },
    { id: "assessment", labelKey: "assessment" },
    { id: "action_and_plan", labelKey: "action_and_plan" },
  ],
};
