import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

const SUBJECT_PREFIX: Record<string, string> = {
  en: "MediTalk Note",
  sk: "MediTalk Správa",
  cs: "MediTalk Zpráva",
};

const VIEW_BUTTON_LABEL: Record<string, string> = {
  en: "View in MediTalk",
  sk: "Zobraziť v MediTalk",
  cs: "Zobrazit v MediTalk",
};

const FOOTER_TEXT: Record<string, string> = {
  en: "This note was generated by MediTalk.",
  sk: "Táto správa bola vygenerovaná systémom MediTalk.",
  cs: "Tato zpráva byla vygenerována systémem MediTalk.",
};

interface SendNoteEmailOptions {
  to: string;
  title: string;
  noteHtml: string;
  viewUrl: string;
  language: string;
}

export function buildSubject(language: string, title: string): string {
  const prefix = SUBJECT_PREFIX[language] || SUBJECT_PREFIX.en;
  return `${prefix} — ${title}`;
}

function buildEmailHtml({
  noteHtml,
  viewUrl,
  language,
}: Pick<SendNoteEmailOptions, "noteHtml" | "viewUrl" | "language">): string {
  const buttonLabel = VIEW_BUTTON_LABEL[language] || VIEW_BUTTON_LABEL.en;
  const footer = FOOTER_TEXT[language] || FOOTER_TEXT.en;

  return `<!DOCTYPE html>
<html lang="${language}">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>MediTalk</title>
</head>
<body style="margin:0;padding:0;background-color:#f9f8f5;font-family:'Figtree',system-ui,-apple-system,sans-serif;color:#232334;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f9f8f5;">
    <tr>
      <td align="center" style="padding:32px 16px;">
        <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;">
          <!-- Header -->
          <tr>
            <td style="padding:24px 32px;border-bottom:1px solid #e6e3db;">
              <span style="font-size:18px;font-weight:600;color:#232334;">MediTalk</span>
            </td>
          </tr>
          <!-- Note content -->
          <tr>
            <td style="padding:24px 32px;">
              <div style="font-size:14px;line-height:1.6;color:#232334;">
                ${noteHtml}
              </div>
            </td>
          </tr>
          <!-- CTA button -->
          <tr>
            <td style="padding:8px 32px 32px;">
              <table role="presentation" cellpadding="0" cellspacing="0">
                <tr>
                  <td style="background-color:#4444ff;border-radius:8px;">
                    <a href="${viewUrl}" target="_blank" style="display:inline-block;padding:10px 24px;color:#ffffff;font-size:14px;font-weight:500;text-decoration:none;">
                      ${buttonLabel}
                    </a>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
          <!-- Footer -->
          <tr>
            <td style="padding:16px 32px;border-top:1px solid #e6e3db;font-size:12px;color:#6b6a73;">
              ${footer}
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;
}

export async function sendNoteEmail({
  to,
  title,
  noteHtml,
  viewUrl,
  language,
}: SendNoteEmailOptions) {
  const from = process.env.EMAIL_FROM || "MediTalk <noreply@meditalk.ai>";
  const subject = buildSubject(language, title);
  const html = buildEmailHtml({ noteHtml, viewUrl, language });

  const { error } = await resend.emails.send({
    from,
    to,
    subject,
    html,
  });

  if (error) {
    throw new Error(`Failed to send email: ${error.message}`);
  }
}
