import { Resend } from "resend";
import { createAdminClient } from "@/lib/supabase/admin";
import { filterEmptySectionsHtml } from "@/lib/parse-note-sections";
import { serverEnv } from "@/lib/env/server";
import { clientEnv } from "@/lib/env/client";

const resend = new Resend(serverEnv.RESEND_API_KEY);

const SUBJECT_PREFIX: Record<string, string> = {
  en: "MediTalk Note",
  sk: "MediTalk Správa",
  cs: "MediTalk Zpráva",
};

const VIEW_BUTTON_LABEL: Record<string, string> = {
  en: "View in MediTalk",
  sk: "Zobraziť v MediTalk",
  cs: "Zobrazit v MediTalk",
};

const FOOTER_TEXT: Record<string, string> = {
  en: "This note was generated by MediTalk.",
  sk: "Táto správa bola vygenerovaná systémom MediTalk.",
  cs: "Tato zpráva byla vygenerována systémem MediTalk.",
};

interface SendNoteEmailOptions {
  to: string;
  title: string;
  noteHtml: string;
  viewUrl: string;
  language: string;
}

export function buildSubject(language: string, title: string): string {
  const prefix = SUBJECT_PREFIX[language] || SUBJECT_PREFIX.en;
  return `${prefix} — ${title}`;
}

function ctaButton(viewUrl: string, label: string): string {
  return `<table role="presentation" cellpadding="0" cellspacing="0">
                    <tr>
                      <td style="background-color:#4444ff;border-radius:8px;">
                        <a href="${viewUrl}" target="_blank" style="display:inline-block;padding:10px 24px;color:#ffffff;font-size:14px;font-weight:500;text-decoration:none;width:132px;text-align:center;">
                          ${label}
                        </a>
                      </td>
                    </tr>
                  </table>`;
}

function buildEmailHtml({
  noteHtml,
  viewUrl,
  language,
}: Pick<SendNoteEmailOptions, "noteHtml" | "viewUrl" | "language">): string {
  const buttonLabel = VIEW_BUTTON_LABEL[language] || VIEW_BUTTON_LABEL.en;
  const footer = FOOTER_TEXT[language] || FOOTER_TEXT.en;
  const cta = ctaButton(viewUrl, buttonLabel);

  return `<!DOCTYPE html>
<html lang="${language}">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>MediTalk</title>
</head>
<body style="margin:0;padding:0;background-color:#f9f8f5;font-family:'Figtree',system-ui,-apple-system,sans-serif;color:#232334;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f9f8f5;">
    <tr>
      <td align="center" style="padding:32px 16px;">
        <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;">
          <!-- Header: logo -->
          <tr>
            <td style="padding:24px 32px;border-bottom:1px solid #e6e3db;">
              <table role="presentation" cellpadding="0" cellspacing="0">
                <tr>
                  <td style="vertical-align:middle;padding-right:12px;">
                    <img src="https://app.meditalk.ai/app-icon.png" alt="MediTalk" width="40" height="40" style="border-radius:8px;display:block;" />
                  </td>
                  <td style="vertical-align:middle;">
                    <span style="font-size:18px;font-weight:600;color:#232334;">MediTalk</span>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
          <!-- CTA -->
          <tr>
            <td style="padding:24px 32px 0;">
              ${cta}
            </td>
          </tr>
          <!-- Note content -->
          <tr>
            <td style="padding:24px 32px;">
              <div style="font-size:14px;line-height:1.6;color:#232334;">
                ${noteHtml}
              </div>
            </td>
          </tr>
          <!-- Bottom CTA -->
          <tr>
            <td style="padding:8px 32px 32px;">
              ${cta}
            </td>
          </tr>
          <!-- Footer -->
          <tr>
            <td style="padding:16px 32px;border-top:1px solid #e6e3db;font-size:12px;color:#6b6a73;">
              ${footer}
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;
}

async function sendNoteEmail({
  to,
  title,
  noteHtml,
  viewUrl,
  language,
}: SendNoteEmailOptions) {
  const from = serverEnv.EMAIL_FROM;
  const subject = buildSubject(language, title);
  const html = buildEmailHtml({ noteHtml, viewUrl, language });

  const { error } = await resend.emails.send({
    from,
    to,
    subject,
    html,
  });

  if (error) {
    throw new Error(`Failed to send email: ${error.message}`);
  }
}

interface DispatchNoteEmailParams {
  userId: string;
  visitId: string;
  title: string;
  noteHtml: string;
  language: string;
}

/**
 * Full email pipeline: resolve user email, generate magic link, filter HTML,
 * and send. Used by both /api/generate (inline) and /api/send-note-email.
 */
export async function dispatchNoteEmail({
  userId,
  visitId,
  title,
  noteHtml,
  language,
}: DispatchNoteEmailParams) {
  const admin = createAdminClient();
  if (!admin) throw new Error("Admin client unavailable");

  const { data: userData } = await admin.auth.admin.getUserById(userId);
  const userEmail = userData?.user?.email;
  if (!userEmail) throw new Error("User email not found");

  const appUrl = clientEnv.NEXT_PUBLIC_APP_URL;
  const encounterPath = `/${language}/encounters/${visitId}`;
  const redirectTo = `${appUrl}${encounterPath}`;

  const { data: linkData } = await admin.auth.admin.generateLink({
    type: "magiclink",
    email: userEmail,
    options: { redirectTo },
  });

  const viewUrl =
    linkData?.properties?.action_link || `${appUrl}${encounterPath}`;

  await sendNoteEmail({
    to: userEmail,
    title,
    noteHtml: filterEmptySectionsHtml(noteHtml),
    viewUrl,
    language,
  });
}
